apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-store.fullname" . }}
  labels:
{{ include "cloud-store.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name:     {{ include "cloud-store.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name:     {{ include "cloud-store.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "cloud-store.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: webdav
          securityContext:
            {{- toYaml .Values.securityContext.core | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name:  USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloud-store.fullname" . }}
                  key:  username
            - name:  PI_FAILSAFE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloud-store.fullname" . }}
                  key:  password

          volumeMounts:
            - name:      data
              mountPath: /var/webdav

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

          resources:
            {{- toYaml .Values.resources.core | nindent 12 }}

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "cloud-store.fullname" . }}-data-claim

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
