apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-store.fullname" . }}
  labels:
{{ include "cloud-store.labels" . | indent 4 }}
data:
  username:   {{ default "webdav" .Values.username | b64enc | quote }}
  password:   {{ randAlphaNum 32 | b64enc | quote }}
