{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cloud-store.serviceAccountName" . }}
  labels:
{{ include "cloud-store.labels" . | indent 4 }}
{{- end -}}
