apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shield.fullname" . }}-config
  labels:
{{ include "shield.labels" . | indent 4 }}
data:
  config.json: |
    {
      "disable_mlock": 1,
      "backend": {
        "file": {
          "path": "/vault/file"
        }
      },
      "listener": {
        "tcp": {
          "address":     "0.0.0.0:8200",
          "tls_disable": 1
        },
      },
      "default_lease_ttl": "168h",
      "max_lease_ttl": "720h"
    }
