apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shield.fullname" . }}
  labels:
{{ include "shield.labels" . | indent 4 }}
data:
  failsafeUsername:   {{ default "admin" .Values.shield.api.failsafe.username | b64enc | quote }}
  failsafePassword:   {{ randAlphaNum 32 | b64enc | quote }}

  prometheusUsername: {{ default "shield" .Values.shield.prometheus.username | b64enc | quote }}
  prometheusPassword: {{ randAlphaNum 32 | b64enc | quote }}
