{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shield.serviceAccountName" . }}
  labels:
{{ include "shield.labels" . | indent 4 }}
{{- end -}}
